---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: sdist
  image: python:3.7
  commands:
  - python setup.py sdist

- name: wheel
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: publish to artifactory
  image: python:3.7
  commands:
  - pip install twine
  - "twine upload dist/*"
  environment:
    TWINE_PASSWORD:
      from_secret: artifactory_password
    TWINE_REPOSITORY_URL: https://artifactory.saltstack.net/artifactory/api/pypi/pypi-local/
    TWINE_USERNAME:
      from_secret: artifactory_username
  when:
    event:
    - push
    - tag

trigger:
  event:
  - pull_request
  - push
  - tag
---
kind: pipeline
name: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    password:
      from_secret: artifactory_password
    registry: docker.artifactory.saltstack.net
    repo: docker.artifactory.saltstack.net/salt-legion
    username:
      from_secret: artifactory_username

trigger:
  event:
  - push
  - tag

---
kind: secret
name: nexus_username

get:
  path: nexus
  name: username

---
kind: secret
name: nexus_password

get:
  path: nexus
  name: password

---
kind: secret
name: artifactory_username

get:
  path: artifactory-deployer
  name: username

---
kind: secret
name: artifactory_password

get:
  path: artifactory-deployer
  name: password

...
